kind: Deployment
apiVersion: apps/v1
metadata:
  name: sanity-deployment
  namespace: shopify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sanity
  template:
    metadata:
      labels:
        app: sanity
    spec:
      containers:
        - name: shopify-sanity
          image: hyysuresh/shopify-sanity:latest
          ports:
            - containerPort: 3333
---
kind: Service
apiVersion: v1
metadata:
  name: sanity-service
  namespace: shopify
spec:
  selector:
    app: sanity
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
  type: ClusterIP